name: Build RepPanel for all HW platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ER-TFT:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setting ER-TFT configuration (HWv1)
      run: cp sdkconfig_ERTFT_WIFI_esp_idf_40 sdkconfig
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@release-v4.0

  build_HWv2:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setting ER-TFT configuration (HWv2)
        run: cp sdkconfig_HWv2_esp_idf_43 sdkconfig
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@release-v4.3
